[marketplaces.openai-bundled]
last_updated = "2026-05-07T17:46:51Z"
source_type = "local"
source = '\\?\C:\Users\Administrator\.codex\.tmp\bundled-marketplaces\openai-bundled'

[plugins."browser-use@openai-bundled"]
enabled = true

[windows]
sandbox = "elevated"
